#!/data/data/com.termux/files/usr/bin/sh
##
##  Additional steps that should be done after installation/upgrade
##  (actually this script is not executed on first installation because
##  of changed environment and previuos binaries are removed)
##

PREFIX="/data/data/com.termux/files/usr"
TMPDIR="/data/data/com.termux/cache"

if [ "${1}" = "configure" ]; then
    # Normally this should be done when Termux session is created (when Termux-RootFS
    # is already installed) but we need make sure that this directory is exist after
    # upgrade.
    if [ ! -e "${TMPDIR}" ]; then
        mkdir -m 700 "${TMPDIR}" > /dev/null 2>&1
    else
        if [ ! -d "${TMPDIR}" ]; then
            rm -rf "${TMPDIR}" > /dev/null 2>&1
            mkdir -m 700 "${TMPDIR}" > /dev/null 2>&1
        fi
    fi

    # double check if TMPDIR is exist, if not, then create tmp directory
    # in $PREFIX, otherwise make a symlink from cache dir to $PREFIX/tmp
    if [ -e "${TMPDIR}" ]; then
        if [ -d "${PREFIX}/tmp" ]; then
            rm -rf "${PREFIX}/tmp" > /dev/null 2>&1
        fi

        if [ ! -e "${PREFIX}/tmp" ]; then
            ln -sr "${TMPDIR}" "${PREFIX}/tmp" > /dev/null 2>&1
        fi
    else
        # fallback to regular tmp directory if cache directory
        # cannot be created
        if [ -L "${PREFIX}/tmp" ]; then
            rm -f "${PREFIX}/tmp" > /dev/null 2>&1
            mkdir -m 700 "${PREFIX}/tmp" > /dev/null 2>&1
        fi
    fi

    # unpack JDK modules
    if [ ! -e "${PREFIX}/lib/jvm/openjdk-9/lib/modules" ]; then
        zcat "${PREFIX}/lib/jvm/openjdk-9/lib/modules.gz" > "${PREFIX}/lib/jvm/openjdk-9/lib/modules" 2>/dev/null
        chmod 600 "${PREFIX}/lib/jvm/openjdk-9/lib/modules" > /dev/null 2>&1
    fi

    # update man database
    makewhatis > /dev/null 2>&1

    # update font cache
    fc-cache > /dev/null 2>&1

    # update mimeinfo.cache
    update-desktop-database "${PREFIX}/share/applications" > /dev/null 2>&1

    # show message after installation is completed
    if [ ! -e "${PREFIX}/var/lib/termux-rootfs/termux-rootfs_configured" ]; then
        echo
        echo "You need to restart Termux application and"
        echo "run command 'termux-setup-rootfs'."
        echo
    else
        echo
        echo "You need to restart Termux application."
        echo
    fi
fi

exit 0
