# share/__fish_build_paths.fish, generated from share/__fish_build_paths.fish.in by the Makefile. DO NOT MANUALLY EDIT THIS FILE!
# This function is generated by the autotools build to "compile in"
# the local "vendor" completions, functions and configuration conf.
# It is sourced by share/config.fish, if it exists.

set __extra_completionsdir /data/data/com.termux/files/usr/share/fish/vendor_completions.d
set __extra_functionsdir /data/data/com.termux/files/usr/share/fish/vendor_functions.d
set __extra_confdir /data/data/com.termux/files/usr/share/fish/vendor_conf.d
